name: publish-beta

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  pypi-publish-beta:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install-poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: install-dependencies
        run: poetry install --no-interaction

      - name: set-dev-version
        run: |
          # NOTE: get current version
          CURRENT_VERSION=$(poetry version -s)
          # NOTE: create dev version with timestamp
          DEV_VERSION="${CURRENT_VERSION}.dev$(date +'%Y%m%d%H%M%S')"
          # NOTE: update version
          poetry version $DEV_VERSION
          echo "[INFO]: set dev version to $DEV_VERSION"

      - name: publish-to-pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
